# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ventum, s.r.o.
email: info@ventum.net
description: > # this means to ignore newlines until "baseurl:"
  Na realitním trhu aktivně působíme již od roku 1998 a poskytujeme
  našim klientům kompletní realitní servis. Všechny naše nabídky jsou
  osobně prověřeny, právní služby pro klienty zajišťuje vždy renomovaná
  advokátní kancelář.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ventum-cz.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  ventum-cz

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# Build settings
gems:
  - jekyll-paginate

paginate: 6
markdown: kramdown
exclude: [vendor, script, Gemfile, .travis.yml]

prose:
  rooturl: '_posts'
  siteurl: 'http://ventum-cz.github.io/'
  media: 'images'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /script
    - /_plugins
  metadata:
    _posts:
      - name: "nahled"
        field:
          element: "text"
          label: "Náhledový obrázek"
            
      - name: "tags"
        field:
          element: "multiselect"
          label: "Přidat nálepky"
          placeholder: "Vybrat nálepky"
          alterable: true
          options:
            - name: "Prodej"
              value: "prodej"
            - name: "Reference"
              value: "reference"
            - name: "Pronájem"
              value: "pronajem"
            - name: "Pozemky"
              value: "pozemek"
            - name: "Poptávky"
              value: "poptavka"

